### ISSUE TITLE
project name in netbeans is <unrecognized project; missing plug-in?>

### ISSUE THREAD

**Issue by SuperPou1** [HelloOO7/BounceTales#1] opened 2023-01-09 20:46 UTC
my netbeans version is 8.2 and i have installed the mobility plugin, are there any more plugins that need to be installed? also i'm running it on wine…

**Comment by HelloOO7** [comment] 2023-01-09 21:07
It should be okay to just use base NetBeans 8.2 with all Java ME plug-ins. That means:
- Java ME Keystore Management
- Java ME Common Ant Tasks
- Mobility
- Java ME Core
- Java ME Project

You may also need to add the proper URL to the NB 8.2 plugin portal, see [here](https://cwiki.apache.org/confluence/display/NETBEANS/Where+to+download+plugins+for+NetBeans+10.0+and+earlier)
For further information, consult [here](https://docs.oracle.com/javame/config/cldc/rel/3.2/get-started-win/setup_devenv.htm) or [here](https://stackoverflow.com/questions/24346193/adding-java-me-platform-in-netbeans-8-0). Just be sure to filter out the Oracle stuff as you're presumably using a Nokia SDK.

**Comment by SuperPou1** [comment] 2023-01-09 21:31
> 

well, i don't have the java me plugins, and after adding the proper url they still aren't avaible to install, also a lot of plugins from the added url can't even download, what do i do in that situation?

**Comment by HelloOO7** [comment] 2023-01-09 21:39
The following plug-ins should be available in all NetBeans 8.2 installations (I'm using this one: https://archive.org/details/jdk-8u111-nb-8_2).
![plugins](https://user-images.githubusercontent.com/20842714/211413136-73ac7af5-bf1b-42f1-b708-17d0fc117cd8.png)
They should be downloadable from the default NB repository (NetBeans distribution).

**Comment by SuperPou1** [comment] 2023-01-09 21:59
> 

i downloaded netbeans from the same exact link as you did, and also turns out, i installed something else than mobility (the category of the plugin was mobility), and also the url i had to add didn't give me an option to install the mobility plugin… help?

**Comment by HelloOO7** [comment] 2023-01-09 22:02
Mobility isn't part of the NB plug-in portal repository, but of the standard NB distribution, which should be active by default in the IDE. If it isn't, it is found at http://updates.netbeans.org/netbeans/updates/8.2/uc/final/distribution/catalog.xml.gz.

**Comment by SuperPou1** [comment] 2023-01-09 22:05
> Mobility isn't part of the NB plug-in portal repository, but of the standard NB distribution, which should be active by default in the IDE. If it isn't, it is found at http://updates.netbeans.org/netbeans/updates/8.2/uc/final/distribution/catalog.xml.gz.

well, then clearly something is wrong, since there were no plugins avaible to install at all when i installed netbeans! could it be that i am running it on wine?

**Comment by HelloOO7** [comment] 2023-01-09 22:17
I don't know, I don't use Wine. All the projects here were tested on Windows.

**Comment by SuperPou1** [comment] 2023-01-09 22:18
> I don't know, I don't use Wine. All the projects here were tested on Windows.

installing plugins manually does work tho - maybe it's possible to download the mobility plugin seperately so i can install it manually?

**Comment by HelloOO7** [comment] 2023-01-09 22:29
You could do that, but Mobility itself isn't enough, and it along with all the other J2ME plug-ins has a lot of dependencies that would be a pain to install manually, if you could even find them.

Here are the module-related contents of my AppData/Roaming/NetBeans/8.2 folder - you can try using those, but apart from that you're on your own, remember, this is an issue tracker, not a support forum.
[8.2.zip](https://github.com/HelloOO7/BounceTales/files/10377389/8.2.zip)

**Comment by SuperPou1** [comment] 2023-01-09 23:00
> You could do that, but Mobility itself isn't enough, and it along with all the other J2ME plug-ins has a lot of dependencies that would be a pain to install manually, if you could even find them.
> 
> Here are the module-related contents of my AppData/Roaming/NetBeans/8.2 folder - you can try using those, but apart from that you're on your own, remember, this is an issue tracker, not a support forum. [8.2.zip](https://github.com/HelloOO7/BounceTales/files/10377389/8.2.zip)

i know mobilty isn't enough, but that is the only thing missing! turns out that the standard nb distribution isn't avaible anymore - i tried searching for files using the web archive, but it hasn't archived it, but all the j2me plugins were avaible to download from oracle, so i guess you just had this plugin downloaded before

**Comment by HelloOO7** [comment] 2023-01-09 23:16
It is available. Its default URL (http://updates.netbeans.org/netbeans/updates/8.2/uc/final/distribution/catalog.xml.gz) still points to a valid catalog that contains all the plug-ins. Not sure why it isn't working for you.

**Comment by SuperPou1** [comment] 2023-01-09 23:26
> It is available. Its default URL (http://updates.netbeans.org/netbeans/updates/8.2/uc/final/distribution/catalog.xml.gz) still points to a valid catalog that contains all the plug-ins. Not sure why it isn't working for you.

Seems like only the catolog works for me - everything under that gives me a 404 error. Maybe try to go to the tab with plugins you can install and press the button at the very top (I don't remember what it said) that will refresh the list - you should get a bunch of errors about it not connecting.

**Comment by HelloOO7** [comment] 2023-01-09 23:28
I did not. I could in fact uninstall and redownload all 33 Mobility modules just fine. What errors are you getting?

**Comment by SuperPou1** [comment] 2023-01-09 23:32
> I did not. I could in fact uninstall and redownload all 33 Mobility modules just fine. What errors are you getting?

That's so weird! It's like, it was blocked in my country or something. The errors I get are just connection errors, like the link to the catalog didn't go anywhere. The other one with different plugins worked half fine. That catalog actually loaded normally but most of the plugins couldn't be downloaded, these has the same connection errors.

**Comment by HelloOO7** [comment] 2023-01-09 23:35
Make sure NetBeans is set not to use a proxy (it uses a system one by default), and if you are suspecting that NBDC is region-blocked for some unknown reason, try with a system-wide VPN. However, I don't see why any government would block a NetBeans plug-in portal...

**Comment by SuperPou1** [comment] 2023-01-09 23:42
![image](https://user-images.githubusercontent.com/52333731/211430008-bb3060b7-aa6f-42bb-a847-42eab0cb1b03.png)
so this is the error i am getting, and yes, i disabled the default set proxy
(when i press skip it gives me the same error for the other urls)

**Comment by HelloOO7** [comment] 2023-01-09 23:49
Could be an SSL problem. It would be wiser to test this on Windows, or with a native build of NB for your OS. At any rate it does not appear to be an issue with neither NetBeans nor BounceTales. Unless there's some sort of problem caused by the projects in this repo, you can probably close this.

**Comment by SuperPou1** [comment] 2023-01-10 17:15
> Could be an SSL problem. It would be wiser to test this on Windows, or with a native build of NB for your OS. At any rate it does not appear to be an issue with neither NetBeans nor BounceTales. Unless there's some sort of problem caused by the projects in this repo, you can probably close this.

i did some further research, i managed to get most of the plugins manually, but i still can't find the mobility plugin itself, the default netbeans repo doesn't have it anymore

**Comment by SuperPou1** [comment] 2023-01-10 17:18
but yeah, i guess i can close this now, because you had the mobility plugin in your appdata, copied it over to mine, and now it works

**Closed as completed** 2023-01-10 17:18 UTC
Labels: build-tools

**Comment by HelloOO7** [comment] 2023-01-10 18:54
The default NB repo does have it, f. e. here: http://updates.netbeans.org/netbeans/updates/8.2/uc/final/distribution/82_patch2/mobility/org-netbeans-modules-mobility-cldcplatform.nbm

In case it goes offline, I will add some backup links to the README, but as it seems like the issue is something local to your system, we'll rely on the NB repo for the time being.

**Comment by SuperPou1** [comment] 2023-01-10 19:25
> The default NB repo does have it, f. e. here: http://updates.netbeans.org/netbeans/updates/8.2/uc/final/distribution/82_patch2/mobility/org-netbeans-modules-mobility-cldcplatform.nbm
> 
> In case it goes offline, I will add some backup links to the README, but as it seems like the issue is something local to your system, we'll rely on the NB repo for the time being.

no, that isn't the mobility plugin, the mobility plugin is `org-netbeans-modules-mobility-kit`, i think, and that cannot be downloaded from there! `org-netbeans-modules-mobility-cldcplatform` is cldc platform in netbeans
![Zrzut ekranu z 2023-01-10 20-22-17](https://user-images.githubusercontent.com/52333731/211643119-a6750847-862e-45e0-8243-31d3270fe785.png)

**Comment by HelloOO7** [comment] 2023-01-10 19:40
The mobility kit is in the NB Certified repo (also included in the default configuration), here: https://updates.netbeans.org/netbeans/updates/8.2/uc/final/certified/82/extra/org-netbeans-modules-mobility-kit.nbm

I think it's probably something in Wine or on your network that prevents the repos from connecting, as otherwise these are normally downloadable over HTTP.
